name: Deploy "master" via AWS SSM

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Deploy via SSM
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::003077251232:role/GithubDeploy
          role-session-name: GitHubActionSession

      - name: sync with beta
        if: success()
        run: |
          set -euo pipefail
          git config user.name  "tech-adtechnology"
          git config user.email "adtechnology@axelspringer.com"
          
          git checkout beta
          git merge master
          git push

      - name: Zip files
        run: |
          zip -r ${{ github.event.repository.name }}_${{ github.ref_name }}.zip ./

      - name: Upload artifact to S3 (temporär)
        run: |
          aws s3 cp ${{ github.event.repository.name }}_${{ github.ref_name }}.zip s3://github-deploy-003077251232/${{ github.event.repository.name }}_${{ github.ref_name }}.zip

      - name: Trigger deploy command via SSM to adtechs
        run: |
          aws ssm send-command \
            --instance-ids i-0b492105afc5cf848 \
            --document-name "arn:aws:ssm:eu-central-1::document/AWS-RunShellScript"  \
            --comment "GitHub Actions Deploy" \
            --parameters '{
              "commands": [
                "aws s3 cp s3://github-deploy-003077251232/${{ github.event.repository.name }}_${{ github.ref_name }}.zip /tmp/${{ github.event.repository.name }}_${{ github.ref_name }}.zip",
                "unzip -o /tmp/${{ github.event.repository.name }}_${{ github.ref_name }}.zip -d /var/www/projects/_workCopies/${{ github.event.repository.name }}",
                "cd /var/www/projects/_workCopies/${{ github.event.repository.name }} && npm i && npm run build && npm run deploy",
                "rm /tmp/${{ github.event.repository.name }}_${{ github.ref_name }}.zip"
              ]
            }' \
            --timeout-seconds 600 \
            --region eu-central-1

  updateBILD:
    runs-on: ubuntu-latest
    needs: deploy
    name: update BILD files

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          path: src

      - name: Run ads.txt deployment
        working-directory: src
        run: |
          npm i
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::003077251232:role/GithubDeploy
          role-session-name: GitHubActionSession

      - name: Retrieve GitHub credentials from AWS Secrets Manager
        id: secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,Github
          parse-json-secrets: true

      - name: Export as output
        id: expose
        run: |
          echo "token=${TECH_ADTECHNOLOGY_OAUTH}" >> "$GITHUB_OUTPUT"

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: spring-media/red-static-content
          ref: main
          token: ${{ steps.expose.outputs.token }}
          path: dest

      - name: Fetch source files
        id: fetch
        shell: bash
        run: |
          set -euo pipefail
          cat dest/bild/bild/ads.txt
          cat src/_dist/bild.de/ads.txt
          cp -u src/_dist/bild.de/ads.txt dest/bild/bild/ads.txt
          cat dest/bild/bild/ads.txt
          cp -u src/_dist/bild.de/app-ads.txt dest/bild/bild/app-ads.txt
          cp -u src/_dist/sportbild.de/ads.txt dest/bild/sportbild/ads.txt
          cp -u src/_dist/sportbild.de/app-ads.txt dest/bild/sportbild/app-ads.txt

      - name: Commit & push changes
        working-directory: dest
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "tech-adtechnology"
          git config user.email "adtechnology@axelspringer.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "updated (app-)ads.txt by adtechs repo hook"
            git push
          else
            echo "No changes to commit."
          fi
